version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: ['--config.file=/etc/prometheus/prometheus.yaml']
    ports:
      - '9090:9090'

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yaml:/etc/alertmanager/config.yaml
    command: ['--config.file=/etc/alertmanager/config.yaml']
    ports:
      - '9093:9093'
