global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alerts.yaml'

scrape_configs:
  - job_name: 'subgraph'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'monitor-dev-subgraph.sceptre.fi'
          - 'monitor-subgraph.sceptre.fi'
