name: release subgraph-monitor

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build binary
        run: cargo build --release

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          make_latest: true
          files: subgraph-monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
